---
- name: Crear usuario userAnsi con acceso SSH y privilegios sudo  
  hosts: all  
  gather_facts: no 
  become: yes 

  vars:
    usuario: userti  # Nombre del usuario a crear
    clave_ssh_publica: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDK0PLkz3R9AThs1q3UJanj2uxcC359ft64kuXfHMCrMk+2Dkl8llQQXfEicZsxLwn/2iPN6AGzp7jeCEEv14kFrhTCTnSwUYyQN96rc/KTIoaiRAMEc5cVyVPlrXtq1euXuDiug2vTvVYoi5fJivc6BvJXumHRb0IRBwzcztra2NZoiVLS64wd6Cuom8NYOxGCAu8tjynXjL5cyYU5tHvk2Y8qyVR5HjXSfA8eqHTj56mGu8Dm1W1J4JIK5SHg9T4dBhwvK+4Bz3BQ65iISjawChl56yO/t4PEecYXMclMY9AdABhrTwy7cDxq9yxG+5UFjPjnM6CzkQdNd363hxI1I1sMc8oYisIE9shTkawfvFhoXS10g92MxtOQtrtyc6jsWcLhVkyzuKWLasIHTHq11/QwkmGv6t5daPk7uIxzvjags+121+5lQ6CxWfsfo3CmV5NYii6rfLedwWAiHOm1fHgwQMLXGzjsw8XSCYOKhfx+6Rl4KaUk8dvZrmkbbTM= Ansible
# Clave pública SSH para acceso al usuario creado

  tasks:
    - name: Crear usuario {{ usuario }} con home y bash
      ansible.builtin.user:
        name: "{{ usuario }}"
        state: present
        create_home: yes
        shell: /bin/bash
        comment: "Usuario con acceso SSH y privilegios sudo"
      register: user_creation_result

    - name: Crear directorio .ssh para el usuario
      ansible.builtin.file:
        path: "/home/{{ usuario }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ usuario }}"
        group: "{{ usuario }}"
      when: user_creation_result.changed

    - name: Agregar clave pública SSH al usuario
      ansible.builtin.authorized_key:
        user: "{{ usuario }}"
        state: present
        key: "{{ clave_ssh_publica }}"
      when: user_creation_result.changed

    - name: Agregar usuario {{ usuario }} al grupo wheel (sudoers en RHEL/AlmaLinux)
      ansible.builtin.user:
        name: "{{ usuario }}"
        groups: wheel
        append: yes
      when: user_creation_result.changed

    - name: Permitir a {{ usuario }} usar sudo sin contraseña
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ usuario }}"
        content: "{{ usuario }} ALL=(ALL) NOPASSWD: ALL\n"
        mode: '0440'
      when: user_creation_result.changed