---
# ==================================================================
# 1. Play sobre TODOS los hosts: Escanea puertos de bases de datos
# ==================================================================

- name: Escaneo de red en busca de puertos de DB
  hosts: semaforos
  gather_facts: no

  tasks:
    - name: Verificar puertos de MySQL
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 3306
        timeout: 4
      register: mysql_port
      ignore_errors: yes

    - name: Verificar puertos de PostgreSQL
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 5432
        timeout: 4
      register: postgres_port
      ignore_errors: yes

    - name: Verificar puertos de SQL Server
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 1433
        timeout: 4
      register: sqlserver_port
      ignore_errors: yes

    - name: Verificar puertos de Oracle
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 1521
        timeout: 4
      register: oracle_port
      ignore_errors: yes

    - name: Verificar puertos de MongoDB
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 27017
        timeout: 4
      register: mongodb_port
      ignore_errors: yes

    - name: Ejecutar y mostrar resultados del escaneo
      ansible.builtin.shell: |
        echo "Resultados del escaneo de puertos de bases de datos:"
        echo "  MySQL (3306):      {{ 'Activo' if mysql_port.elapsed < 3 else 'Inactivo' }}"
        echo "  PostgreSQL (5432): {{ 'Activo' if postgres_port.elapsed < 3 else 'Inactivo' }}"
        echo "  SQL Server (1433): {{ 'Activo' if sqlserver_port.elapsed < 3 else 'Inactivo' }}"
        echo "  Oracle (1521):     {{ 'Activo' if oracle_port.elapsed < 3 else 'Inactivo' }}"
        echo "  MongoDB (27017):   {{ 'Activo' if mongodb_port.elapsed < 3 else 'Inactivo' }}"
      delegate_to: localhost
      register: scan_output

    - name: Mostrar resultados en consola
      ansible.builtin.debug:
        msg: "{{ scan_output.stdout_lines }}"
