---
# ==================================================================
# 1. Play sobre TODOS los hosts: Escanea puertos de bases de datos
# ==================================================================

- name: Escaneo de red en busca de puertos de DB
  hosts: semaforos
  gather_facts: yes
  vars:
    ruta_json_remoto: "/tmp/info_{{ inventory_hostname}}.json"

  tasks:
    - name: Verificar puertos de MySQL
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 3306
        timeout: 4
      register: mysql_port
      ignore_errors: yes

    - name: Verificar puertos de PostgreSQL
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 5432
        timeout: 4
      register: postgres_port
      ignore_errors: yes

    - name: Verificar puertos de SQL Server
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 1433
        timeout: 4
      register: sqlserver_port
      ignore_errors: yes

    - name: Verificar puertos de Oracle
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 1521
        timeout: 4
      register: oracle_port
      ignore_errors: yes

    - name: Verificar puertos de MongoDB
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 27017
        timeout: 4
      register: mongodb_port
      ignore_errors: yes

    - name: Consolidar puertos abiertos
      set_fact:
        puertos_db:
          mysql:      "{{ mysql_port    is defined and mysql_port   .elapsed < 3 }}"
          postgresql: "{{ postgres_port is defined and postgres_port.elapsed < 3 }}"
          sqlserver:  "{{ sqlserver_port is defined and sqlserver_port.elapsed < 3 }}"
          oracle:     "{{ oracle_port   is defined and oracle_port  .elapsed < 3 }}"
          mongodb:    "{{ mongodb_port  is defined and mongodb_port .elapsed < 3 }}"

    - name: Guardar facts + puertos en JSON
      copy:
        content: "{{ ansible_facts
                     | combine({'inventory_hostname': inventory_hostname})
                     | combine(puertos_db)            }}"
        dest: "{{ ruta_json_remoto }}"
