---
# ==================================================================
# 1. Play sobre TODOS los hosts: Escanea puertos de bases de datos
# ==================================================================

- name: Escaneo de red en busca de puertos de DB
  hosts: semaforos
  gather_facts: no
  vars:
    # Definimos la lista de servicios para centralizar el mantenimiento
    servicios_db:
      - { nombre: 'MySQL', puerto: 3306 }
      - { nombre: 'PostgreSQL', puerto: 5432 }
      - { nombre: 'SQL Server', puerto: 1433 }
      - { nombre: 'Oracle', puerto: 1521 }
      - { nombre: 'MongoDB', puerto: 27017 }

  tasks:
    - name: "Verificando disponibilidad de puertos"
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ item.puerto }}"
        timeout: 2
        msg: "Timeout"
      loop: "{{ servicios_db }}"
      register: scan_results
      ignore_errors: yes
      # no_log evita que se muestre el "FAILED" gigante en rojo por cada puerto cerrado
      no_log: true

    - name: "RESUMEN DE ESTADO DE BASES DE DATOS"
      ansible.builtin.debug:
        msg: >
          {{ item.item.nombre }} ({{ item.item.puerto }}): 
          {{ 'ABIERTO' if item.failed is not defined or not item.failed else 'CERRADO' }}
      loop: "{{ scan_results.results }}"
      loop_control:
        # Esto hace que en el log solo veas el nombre de la DB, no todo el objeto JSON
        label: "{{ item.item.nombre }}"

    - name: "Consolidar puertos abiertos en una variable (Opcional)"
      set_fact:
        puertos_encontrados: "{{ scan_results.results | map(attribute='item.nombre') | list }}"
      when: not item.failed
      loop: "{{ scan_results.results }}"
      loop_control:
        label: "{{ item.item.nombre }}"
