---
- name: Auditoria Profesional de Puertos y Servicios
  hosts: semaforos
  become: yes
  gather_facts: no

  tasks:
    - name: "PASO 1: Capturar puertos en escucha"
      # Usamos un delimitador claro (coma) para que no haya dudas al separar
      ansible.builtin.shell: "ss -tunlp | grep LISTEN | awk '{print $1\",\"$5\",\"$7}'"
      register: raw_network_data
      changed_when: false

    - name: "PASO 2: Inicializar lista de servicios"
      set_fact:
        servicios_lista: []

    - name: "PASO 3: Parsear líneas una a una"
      set_fact:
        servicios_lista: "{{ servicios_lista + [{'protocolo': item.split(',')[0], 'puerto': item.split(',')[-1].split(':')[-1], 'proceso': item.split('\"')[1] | default('desconocido')}] }}"
      loop: "{{ raw_network_data.stdout_lines }}"
      when: 
        - raw_network_data.stdout_lines | length > 0
        - '"' in item # Solo procesa si hay un nombre de proceso entre comillas

    - name: "PASO 4: Informe visual final"
      ansible.builtin.debug:
        msg: |
          REPORTE DE SERVICIOS - {{ inventory_hostname }}
          ----------------------------------------------
          {% for svc in servicios_lista %}
          - [{{ '%-3s' | format(svc.protocolo | upper) }}] Puerto: {{ '%-6s' | format(svc.puerto) }} -> Servicio: {{ svc.proceso }}
          {% endfor %}
          ----------------------------------------------
          Total servicios detectados: {{ servicios_lista | length }}
      when: servicios_lista | length > 0
