---
# ==============================================================
# 1. Play sobre TODOS los hosts: recopila facts, muestra resumen
#    y copia cada JSON al nodo de control
# ==============================================================

- name: Recopilar facts y copiarlos al controlador
  hosts: semaforos
  gather_facts: yes
  become: true

  vars:
    ruta_json_remoto: "/tmp/info_{{ inventory_hostname }}.json"
    ruta_json_ctl:    "/home/semaphore/Excels"

  pre_tasks:
    # Creamos la carpeta en el nodo de control (una sola vez)
    - name: Crear carpeta local para los JSON
      file:
        path: "{{ ruta_json_ctl }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      run_once: true
      become: false

  tasks:
    # ----------------------------------------------------------
    # 1) RESUMEN legible en consola (lo que acabará en el Excel)
    # ----------------------------------------------------------
    - name: Construir resumen para Excel
      set_fact:
        excel_summary:
          IP: "{{ ansible_default_ipv4.address | default(inventory_hostname) }}"
          Hostname: "{{ ansible_hostname }}"
          SO: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          Kernel: "{{ ansible_kernel }}"
          Arquitectura: "{{ ansible_architecture }}"
          CPU: "{{ ansible_processor[2] | default(ansible_processor[-1]) }}"
          RAM_Total_GB: "{{ (ansible_memtotal_mb | int / 1024) | round(0, 'ceil') | int }}"
          RAM_Libre_GB: "{{ (ansible_memfree_mb  | int / 1024) | round(0, 'ceil') | int }}"
          # ---------- disco montado ----------
          Disco_Total_GB: >-
            {{
              (ansible_mounts
                | selectattr('device','match','^/dev/(sd|nvme)')
                | map(attribute='size_total')
                | sum
                | float / 1073741824) | round(2)
            }}
          Disco_Libre_GB: >-
            {{
              (ansible_mounts
                | selectattr('device','match','^/dev/(sd|nvme)')
                | map(attribute='size_available')
                | sum
                | float / 1073741824) | round(2)
            }}
          Tipo_maquina: "{{ 'Virtual' if ansible_virtualization_role == 'guest' else 'Física' }}"



    - name: Mostrar resumen en consola
      debug:
        var: excel_summary

    # ----------------------------------------------------------
    # 2) Guardar los facts en JSON (incluye inventory_hostname)
    # ----------------------------------------------------------
    - name: Guardar facts del sistema en JSON en el host
      copy:
        content: "{{ ansible_facts
                     | combine({'inventory_hostname': inventory_hostname})
                     | to_nice_json }}"
        dest: "{{ ruta_json_remoto }}"

    - name: Traer JSON al nodo de control
      fetch:
        src: "{{ ruta_json_remoto }}"
        dest: "{{ ruta_json_ctl }}/"
        flat: true


# ==============================================================
# 2. Play LOCAL: genera el Excel con los JSON ya copiados
# ==============================================================

- name: Generar Excel a partir de los JSON (control-node)
  hosts: localhost
  gather_facts: no
  become: false

  vars:
    ruta_json_ctl: "/home/semaphore/Excels"
    script_python: "/home/semaphore/Excels/generar_excel.py"
    ruta_excel:    "/home/semaphore/Excels/Inventario_Equipos_DMZ.xlsx"

  tasks:
    - name: Copiar (o actualizar) script Python
      copy:
        src: "./generar_excel.py"
        dest: "{{ script_python }}"
        mode: "0755"
        force: false

    - name: Ejecutar script para generar el Excel
      command: >
        python3 {{ script_python }}
        {{ ruta_excel }}
        {{ ruta_json_ctl }}/info_*.json
      register: excel_gen

    - name: Mostrar salida del script
      debug:
        var: excel_gen.stdout

    - name: Copiar Excel al directorio final del usuario
      copy:
        src: "{{ ruta_excel }}"
        dest: "/home/userti/Documentos/Excels/Inventario_Equipos_DMZ.xlsx"
        mode: "0644"

# ==============================================================
# 3. Play LOCAL: copiar el excel a equipo windows
# ==============================================================

- name: copiar el excel al windows
  hosts: Pc_Windows
  gather_facts: no
  become: false
  tasks:
    
    - name: Crear carpeta destino si no existe
      shell: |
        if (-not (Test-Path 'C:\Users\pedfer4218\Desktop\InventarioEquiposDMZ')) {
          Nem-Item -ItemType Directory -Path 'C:\Users\pedfer4218\Desktop\InventarioEquiposDMZ' | Out-Null
        }
    
    - name: copiar Excel mediant modulo copy (usa SFTP)
      copy:
        src: "/home/semaphore/Excels/Inventario_Equipos_DMZ.xlsx"
        dest: C:\Users\pedfer4218\Desktop\InventarioEquiposDMZ\Inventario_Equipos_DMZ.xlsx
        mode: "0644"