---
########################################################################
# 1. Linux (semaforos): facts + PUERTOS → JSON → fetch al nodo control #
########################################################################
- name: Recoger facts y escanear puertos
  hosts: semaforos
  gather_facts: yes
  become: true                                      # escribir /tmp y usar ss

  vars:
    ruta_json_remoto: "/tmp/info_{{ inventory_hostname }}.json"
    ruta_json_ctl:    "/home/semaphore/Excels"

  # -------------------------------------------------------------------
  # PRE  : crear la carpeta local solo una vez
  # -------------------------------------------------------------------
  pre_tasks:
    - name: Crear carpeta local para los JSON
      file:
        path: "{{ ruta_json_ctl }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      run_once: true
      become: false

  tasks:
  # -------------------------------------------------------------------
  # 1A) Escaneo rápido de PUERTOS de bases de datos (método wait_for)
  # -------------------------------------------------------------------
    - name: Verificar MySQL (3306)      # todas estas tareas siguen igual
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 3306
        timeout: 4
      register: mysql_port
      ignore_errors: yes

    - name: Verificar PostgreSQL (5432)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 5432
        timeout: 4
      register: postgres_port
      ignore_errors: yes

    - name: Verificar SQL Server (1433)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 1433
        timeout: 4
      register: sqlserver_port
      ignore_errors: yes

    - name: Verificar Oracle (1521)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 1521
        timeout: 4
      register: oracle_port
      ignore_errors: yes

    - name: Verificar MongoDB (27017)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 27017
        timeout: 4
      register: mongodb_port
      ignore_errors: yes

    - name: Consolidar resultado de puertos DB
      set_fact:
        puertos_db:
          mysql:      "{{ mysql_port    is defined and mysql_port.elapsed     < 3 }}"
          postgresql: "{{ postgres_port is defined and postgres_port.elapsed  < 3 }}"
          sqlserver:  "{{ sqlserver_port is defined and sqlserver_port.elapsed < 3 }}"
          oracle:     "{{ oracle_port   is defined and oracle_port.elapsed    < 3 }}"
          mongodb:    "{{ mongodb_port  is defined and mongodb_port.elapsed   < 3 }}"

  # -------------------------------------------------------------------
  # 1B) NUEVO: listar TODOS los puertos TCP/UDP en escucha con ss/netstat
  # -------------------------------------------------------------------
    - name: Obtener puertos TCP/UDP en escucha (ss)
      shell: |
        ss -lntuH | awk '{print $5}' | awk -F':' '{print $NF}' | sort -n | uniq
      register: listening_ports_cmd
      changed_when: false
      failed_when: false        # por si ss no existe

    - name: (Fallback) Obtener puertos de netstat si ss no está disponible
      shell: |
        netstat -lntu 2>/dev/null | awk 'NR>2 {print $4}' | awk -F':' '{print $NF}' | sort -n | uniq
      register: listening_ports_netstat
      changed_when: false
      when: listening_ports_cmd.rc != 0

    - name: Definir lista final de puertos en escucha
      set_fact:
        listening_ports: >-
          {{
            (listening_ports_cmd.rc == 0
             and listening_ports_cmd.stdout_lines
             or listening_ports_netstat.stdout_lines)
          }}

    - name: Mostrar puertos en escucha
      debug:
        msg: "Puertos en escucha en {{ inventory_hostname }}: {{ listening_ports }}"
    
    - name: Obtener usuarios y grupos
      shell: |
        echo "Usuarios del sistema:" && getent passwd | awk -F: '{ print $1 " (UID: " $3 ", GID: " $4 ", Shell: " $7 ")" }'
        echo "" && echo "Grupos del sistema:" && getent group
      register: salida_usuarios
      args:
        executable: /bin/bash

    - name: Mostrar usuarios y grupos
      debug:
        msg: "{{ salida_usuarios.stdout_lines }}"

  # -------------------------------------------------------------------
  # 1C) Guardar facts + puertos → JSON y traerlo al control
  # -------------------------------------------------------------------
    - name: Guardar facts + puertos en JSON en el host
      copy:
        content: "{{ ansible_facts
                     | combine(puertos_db)
                     | combine({'listening_ports': listening_ports})
                     | combine({'usuarios': salida_usuarios.stdout_lines})
                     | combine({'inventory_hostname': inventory_hostname})
                     | to_nice_json }}"
        dest: "{{ ruta_json_remoto }}"
        force: yes

    - name: Traer JSON al nodo de control
      fetch:
        src: "{{ ruta_json_remoto }}"
        dest: "{{ ruta_json_ctl }}/"
        flat: true

#############################################################
# 2. localhost: genera/actualiza Inventario_Equipos_DMZ.xlsx #
#############################################################
- name: Generar Excel a partir de los JSON
  hosts: localhost
  gather_facts: no
  vars:
    ruta_json_ctl: "/home/semaphore/Excels"
    script_python: "/home/semaphore/Excels/generar_excel.py"
    ruta_excel:    "/home/semaphore/Excels/Inventario_Equipos_DMZ.xlsx"

  tasks:
    - name: Copiar / actualizar script Python
      copy:
        src: "./generar_excel.py"
        dest: "{{ script_python }}"
        mode: "0755"
        force: false

    - name: Ejecutar script para generar el Excel
      command: >
        python3 {{ script_python }}
        {{ ruta_excel }}
        {{ ruta_json_ctl }}/info_*.json
      register: excel_gen

    - debug:
        var: excel_gen.stdout

################################################################
# 3. Windows: copiar al share \\srvctdep02\Deploy\Ansible ######
################################################################
- name: Copiar inventario a Ruta de red (directamente desde el nodo de control)
  hosts: localhost
  gather_facts: no

  vars:
    src_dir:    "/home/semaphore/Excels"
    excel_file: "Inventario_Equipos_DMZ.xlsx"
    txt_file:   "Inventario_Equipos_DMZ.txt"
    smb_share:  "//10.49.1.110/Deploy/Ansible"
    smb_user: "{{ lookup('env', 'win_user') }}"
    smb_pass: "{{ lookup('env', 'win_password_privilegios') }}"
    mountpoint: "/mnt/ansible_share"

  tasks:
    - name: Verificar credenciales
      debug:
        msg: |
          smb_user = {{ smb_user }}
          pass_len = {{ smb_pass | length }}

    - name: Asegurarse de que cifs-utils está instalado
      become: true
      ansible.builtin.package:
        name: cifs-utils
        state: present

    - name: Crear punto de montaje local
      become: true
      file:
        path: "{{ mountpoint }}"
        state: directory
        mode: "0755"

    - name: Desmontar si ya está montado
      become: true
      shell: |
        mountpoint -q "{{ mountpoint }}" && umount "{{ mountpoint }}" || true
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Montar recurso compartido SMB
      become: true
      shell: |
        mount -t cifs "{{ smb_share }}" "{{ mountpoint }}" \
          -o username="{{ smb_user }}",password="{{ smb_pass }}",rw
      args:
        executable: /bin/bash
      register: mount_result
      failed_when: mount_result.rc != 0
      ignore_errors: true

    - name: Mostrar error si falla el montaje del recurso SMB
      fail:
        msg: "❌ Error al montar el recurso compartido SMB: {{ smb_share }}"
      when: mount_result.rc != 0

    - name: Copiar archivos al recurso compartido
      copy:
        src: "{{ src_dir }}/{{ item }}"
        dest: "{{ mountpoint }}/{{ item }}"
        mode: "0644"
      loop:
        - "{{ excel_file }}"
        - "{{ txt_file }}"
      become: true

    - name: Desmontar recurso SMB
      become: true
      shell: umount "{{ mountpoint }}"
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: ✅ Copia completada correctamente
      debug:
        msg: "✅ Archivos copiados correctamente al recurso SMB: {{ smb_share }}"





