##########################################################
# 1) Recoger usuarios (Linux/Windows)                    #
##########################################################
- name: Recoger usuarios no-servicio y traer JSON al controlador
  hosts: semaforos
  gather_facts: yes
  become: true

  pre_tasks:
    - name: Limpiar JSON antiguos del controlador antes de empezar
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/home/semaphore/Excels/info_*.json"
      delegate_to: localhost
      run_once: true
      become: false

  # ... resto de tus tareas de fetch ...

##########################################################
# 2) Localhost: Procesar Excel                           #
##########################################################
- name: Actualizar Excel
  hosts: localhost
  gather_facts: no
  vars:
    ruta_json_ctl: "/home/semaphore/Excels"
    ruta_excel:    "/home/semaphore/Excels/Inventario_Equipos_usuarios.xlsx"
    script_python: "/home/semaphore/Excels/append_excel2.py"
    venv_path:     "/home/semaphore/Excels/.venv"

  tasks:
    - name: Crear Script Python
      copy:
        dest: "{{ script_python }}"
        mode: "0755"
        content: |
          #!/usr/bin/env python3
          import sys, os, json
          from openpyxl import Workbook, load_workbook

          def run():
              ex_p, j_p = sys.argv[1], sys.argv[2]
              with open(j_p, 'r') as f: 
                  data = json.load(f)
              
              hn = data.get('inventory_hostname', 'Desconocido')
              us = data.get('usuarios', [])
              # Convertimos a string por si vienen objetos
              us_str = ", ".join([str(u) for u in us])

              if os.path.exists(ex_p):
                  wb = load_workbook(ex_p)
                  ws = wb.active
              else:
                  wb = Workbook()
                  ws = wb.active
                  ws.append(["Hostname", "Usuarios"])

              ws.append([hn, us_str])
              wb.save(ex_p)

          if __name__ == "__main__":
              run()

    - name: Ejecutar script para cada JSON
      shell: |
        [ -d {{ venv_path }} ] || python3 -m venv {{ venv_path }}
        {{ venv_path }}/bin/pip install openpyxl --quiet
        {{ venv_path }}/bin/python {{ script_python }} {{ ruta_excel }} {{ item }}
      with_fileglob:
        - "{{ ruta_json_ctl }}/info_*.json"
      
############################################################
# 3) Copiar el Excel al recurso compartido ya MONTADO      #
############################################################
- name: Copiar Inventario al recurso de red
  hosts: localhost
  gather_facts: no

  vars:
    ruta_excel:  "/home/semaphore/Excels/Inventario_Equipos_usuarios.xlsx"   # mismo que en el play 2
    mountpoint:  "/mnt/ansible_share"                                   # punto de montaje ya existente
    destino:     "Inventario_Usuarios_Equipos_DMZ.xlsx"                           # nombre en el share

  tasks:
    - name: Verificar que el Excel existe en local
      ansible.builtin.stat:
        path: "{{ ruta_excel }}"
      register: excel_stat

    - name: Fallar si no existe el Excel (revisa el play 2)
      ansible.builtin.fail:
        msg: "❌ No existe {{ ruta_excel }}. Asegúrate de que el play 2 lo creó."
      when: not excel_stat.stat.exists

    - name: Verificar que el recurso está montado
      ansible.builtin.stat:
        path: "{{ mountpoint }}"
      register: mount_stat

    - name: Fallar si no está montado
      ansible.builtin.fail:
        msg: "❌ El recurso {{ mountpoint }} no está montado. Móntalo antes de copiar."
      when: not mount_stat.stat.exists

    - name: Crear carpeta destino si no existe
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        state: directory
        mode: "0755"

    - name: Copiar Excel al recurso compartido
      become: true
      ansible.builtin.copy:
        src: "{{ ruta_excel }}"
        dest: "{{ mountpoint }}/{{ destino }}"
        mode: "0644"
        remote_src: true   # <-- el src ya está en esta máquina (localhost)
      register: copy_excel

    - name: Confirmación
      ansible.builtin.debug:
        msg: "✅ Copiado {{ ruta_excel }} -> {{ mountpoint }}/{{ destino }}"
