##########################################################
# 1) Recoger usuarios (Linux/Windows) -> JSON -> fetch   #
##########################################################
- name: Recoger usuarios no-servicio y traer JSON al controlador
  hosts: semaforos
  gather_facts: yes
  become: true
  vars:
    ruta_json_remoto: "/tmp/info_{{ inventory_hostname }}.json"
    ruta_json_ctl:    "/home/semaphore/Excels"
    min_uid: 1000

  tasks:
    - name: Detectar SO
      set_fact:
        es_windows: "{{ ansible_os_family == 'Windows' }}"

    - name: Linux - Obtener usuarios
      when: not es_windows
      shell: "getent passwd | awk -F: '($3 >= {{ min_uid }}) && ($7 !~ /(nologin|false)/) { print $1 }'"
      register: salida_linux
      changed_when: false

    - name: Windows - Obtener usuarios
      when: es_windows
      ansible.windows.win_shell: "Get-LocalUser | Where-Object { $_.Enabled } | Select-Object -ExpandProperty Name"
      register: windows_user_groups
      changed_when: false

    - name: Guardar JSON en remoto
      copy:
        dest: "{{ ruta_json_remoto }}"
        content: |
          {
            "inventory_hostname": "{{ inventory_hostname }}",
            "usuarios": {{ (es_windows | ternary(windows_user_groups.stdout_lines | default([]), salida_linux.stdout_lines | default([]))) | to_json }}
          }

    - name: Traer JSON al controlador
      fetch:
        src: "{{ ruta_json_remoto }}"
        dest: "{{ ruta_json_ctl }}/"
        flat: true

##########################################################
# 2) Localhost: Procesar Excel                           #
##########################################################
- name: Actualizar Excel
  hosts: localhost
  gather_facts: no
  vars:
    ruta_json_ctl: "/home/semaphore/Excels"
    ruta_excel:    "/home/semaphore/Excels/Inventario_Equipos_usuarios.xlsx"
    script_python: "/home/semaphore/Excels/append_excel2.py"
    venv_path:     "/home/semaphore/Excels/.venv"

  tasks:
    - name: Limpiar JSON antiguos (Para no repetir datos)
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ query('fileglob', ruta_json_ctl + '/*.json') }}"

    - name: Crear Script Python (AUTOMÁTICO)
      copy:
        dest: "{{ script_python }}"
        mode: "0755"
        content: |
          #!/usr/bin/env python3
          import sys, os, json
          from openpyxl import Workbook, load_workbook

          ex_p, j_p = sys.argv[1], sys.argv[2]
          with open(j_p, 'r') as f: data = json.load(f)
          
          if os.path.exists(ex_p):
              wb = load_workbook(ex_p)
              ws = wb.active
          else:
              wb = Workbook()
              ws = wb.active
              ws.append(["Hostname", "Usuarios"])

          ws.append([data['inventory_hostname'], ", ".join(data['usuarios'])])
          wb.save(ex_p)

    - name: Preparar Python y Ejecutar
      shell: |
        python3 -m venv {{ venv_path }}
        {{ venv_path }}/bin/pip install openpyxl
        {{ venv_path }}/bin/python {{ script_python }} {{ ruta_excel }} {{ item }}
      loop: "{{ query('fileglob', ruta_json_ctl + '/*.json') }}"
      
############################################################
# 3) Copiar el Excel al recurso compartido ya MONTADO      #
############################################################
- name: Copiar Inventario al recurso de red
  hosts: localhost
  gather_facts: no

  vars:
    ruta_excel:  "/home/semaphore/Excels/Inventario_Equipos_usuarios.xlsx"   # mismo que en el play 2
    mountpoint:  "/mnt/ansible_share"                                   # punto de montaje ya existente
    destino:     "Inventario_Usuarios_Equipos_DMZ.xlsx"                           # nombre en el share

  tasks:
    - name: Verificar que el Excel existe en local
      ansible.builtin.stat:
        path: "{{ ruta_excel }}"
      register: excel_stat

    - name: Fallar si no existe el Excel (revisa el play 2)
      ansible.builtin.fail:
        msg: "❌ No existe {{ ruta_excel }}. Asegúrate de que el play 2 lo creó."
      when: not excel_stat.stat.exists

    - name: Verificar que el recurso está montado
      ansible.builtin.stat:
        path: "{{ mountpoint }}"
      register: mount_stat

    - name: Fallar si no está montado
      ansible.builtin.fail:
        msg: "❌ El recurso {{ mountpoint }} no está montado. Móntalo antes de copiar."
      when: not mount_stat.stat.exists

    - name: Crear carpeta destino si no existe
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        state: directory
        mode: "0755"

    - name: Copiar Excel al recurso compartido
      become: true
      ansible.builtin.copy:
        src: "{{ ruta_excel }}"
        dest: "{{ mountpoint }}/{{ destino }}"
        mode: "0644"
        remote_src: true   # <-- el src ya está en esta máquina (localhost)
      register: copy_excel

    - name: Confirmación
      ansible.builtin.debug:
        msg: "✅ Copiado {{ ruta_excel }} -> {{ mountpoint }}/{{ destino }}"
