---
- name: Obtener información detallada del equipo y generar Excel
  hosts: all
  gather_facts: yes
  become: true

  vars:
    ruta_json: "/tmp/info_{{ inventory_hostname }}.json"
    ruta_excel: "/home/userti/Documentos/Inventario_Equipos_DMZ.xlsx"
    script_python: "/tmp/generar_excel.py"

  tasks:

    - name: Mostrar el nombre del equipo (hostname)
      debug:
        msg: "Nombre del equipo: {{ ansible_hostname }}"

    - name: Mostrar información del sistema operativo
      debug:
        msg:
          - "Sistema operativo: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "Arquitectura: {{ ansible_architecture }}"

    - name: Mostrar información de la CPU
      debug:
        msg:
          - "Modelo CPU: {{ ansible_processor[2] | default(ansible_processor[-1]) }}"
          - "Número de núcleos (físicos): {{ ansible_processor_cores }}"
          - "Número total de procesadores lógicos: {{ ansible_processor_count }}"

    - name: Mostrar memoria RAM total
      debug:
        msg: "Memoria RAM: {{ (ansible_memtotal_mb | int / 1024) | round(2) }} GB"

    - name: Mostrar información del disco
      debug:
        msg: >-
          {% for device, data in ansible_devices.items() if device.startswith('sd') or device.startswith('nvme') %}
          Disco {{ device }} - Tamaño: {{ data.size }}
          {% endfor %}

    - name: Detección de máquina física o virtual
      debug:
        msg: >-
          {% if ansible_virtualization_role == 'guest' %}
            Es una MÁQUINA VIRTUAL ({{ ansible_virtualization_type }}).
          {% elif ansible_virtualization_role == 'host' %}
            Es un HOST de virtualización ({{ ansible_virtualization_type }}).
          {% else %}
            Es un EQUIPO FÍSICO (sin virtualización detectable).
          {% endif %}

    - name: Guardar datos del sistema en JSON
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "{{ ruta_json }}"

    - name: Copiar script Python que genera el Excel
      copy:
        src: "./generar_excel.py"
        dest: "{{ script_python }}"
        mode: '0755'

    - name: Instalar pandas si no está instalado
      ansible.builtin.apt:
        name: python3-pandas
        state: present
        update_cache: yes

    - name: Generar Excel con la información recolectada
      command: "python3 {{ script_python }} {{ ruta_excel }} /tmp/info_*.json"
      run_once: true

    - name: Copiar Excel al equipo local
      fetch:
        src: "{{ ruta_excel }}"
        dest: "/home/userti/Documentos/Inventario_Equipos_DMZ.xlsx"
        flat: true
      run_once: true
