---
- name: Obtener información detallada del equipo y generar Excel
  hosts: all
  gather_facts: yes
  become: true

  vars:
    ruta_json: "/tmp/info_{{ inventory_hostname }}.json"
    ruta_json_local: "/home/semaphore/Excels"
    script_python: "/tmp/generar_excel.py"
    ruta_excel: "/home/semaphore/Excels/Inventario_Equipos_DMZ.xlsx"

  tasks:

    - name: Mostrar el nombre del equipo (hostname)
      debug:
        msg: "Nombre del equipo: {{ ansible_hostname }}"

    - name: Mostrar información del sistema operativo
      debug:
        msg:
          - "Sistema operativo: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "Arquitectura: {{ ansible_architecture }}"

    - name: Mostrar información de la CPU
      debug:
        msg:
          - "Modelo CPU: {{ ansible_processor[2] | default(ansible_processor[-1]) }}"
          - "Número de núcleos (físicos): {{ ansible_processor_cores }}"
          - "Número total de procesadores lógicos: {{ ansible_processor_count }}"

    - name: Mostrar memoria RAM total
      debug:
        msg: "Memoria RAM: {{ (ansible_memtotal_mb | int / 1024) | round(2) }} GB"

    - name: Mostrar información del disco
      debug:
        msg: >-
          {% for device, data in ansible_devices.items() if device.startswith('sd') or device.startswith('nvme') %}
          Disco {{ device }} - Tamaño: {{ data.size }}
          {% endfor %}

    - name: Detección de máquina física o virtual
      debug:
        msg: >-
          {% if ansible_virtualization_role == 'guest' %}
            Es una MÁQUINA VIRTUAL ({{ ansible_virtualization_type }}).
          {% elif ansible_virtualization_role == 'host' %}
            Es un HOST de virtualización ({{ ansible_virtualization_type }}).
          {% else %}
            Es un EQUIPO FÍSICO (sin virtualización detectable).
          {% endif %}

    - name: Guardar datos del sistema en JSON en el cliente
      copy:
        content: "{{ ansible_facts | combine({'inventory_hostname': inventory_hostname}) | to_nice_json }}"
        dest: "{{ ruta_json }}"

    - name: Copiar JSON al nodo de control (Semaphore)
      fetch:
        src: "{{ ruta_json }}"
        dest: "{{ ruta_json_local }}/"
        flat: true

  # Esta parte se ejecuta solo una vez en el nodo de control
    - name: Generar Excel en el nodo local con los JSON recolectados
      hosts: localhost
      gather_facts: no
      tasks:

      - name: Asegurarse de que exista la carpeta local para recibir el Excel
        file:
          path: "/home/userti/Documentos/Excels"
          state: directory
          mode: '0777'

      - name: Copiar script Python al nodo local (Semaphore)
        copy:
          src: "./generar_excel.py"
          dest: "{{ script_python }}"
          mode: '0755'

      - name: Instalar pandas y openpyxl si no están instalados (solo si es Debian/Ubuntu)
        ansible.builtin.apt:
          name:
            - python3-pandas
            - python3-openpyxl
          state: present
          update_cache: yes
        become: true

      - name: Ejecutar script Python para generar Excel con la información
        command: "python3 {{ script_python }} {{ ruta_excel }} {{ ruta_json_local }}/info_*.json"

      - name: Copiar Excel generado al directorio final del usuario
        copy:
          src: "{{ ruta_excel }}"
          dest: "/home/userti/Documentos/Excels/Inventario_Equipos_DMZ.xlsx"
