##########################################################
# 1) Recoger TODOS los usuarios y sus Grupos             #
##########################################################
- name: Recoger usuarios y permisos
  hosts: semaforos
  gather_facts: yes
  become: true
  vars:
    ruta_json_remoto: "/tmp/info_{{ inventory_hostname }}.json"
    ruta_json_ctl:    "/home/semaphore/Excels"

  pre_tasks:
    - name: Limpieza inicial
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob: ["{{ ruta_json_ctl }}/info_*.json"]
      delegate_to: localhost
      run_once: true
      become: false

  tasks:
    - name: Detectar SO
      ansible.builtin.set_fact:
        es_windows: "{{ ansible_os_family == 'Windows' }}"

    # Linux: Formato "usuario:grupo1,grupo2"
    - name: Linux - Obtener todos los usuarios y sus grupos
      when: not es_windows
      ansible.builtin.shell: |
        for u in $(cut -d: -f1 /etc/passwd); do
          groups_list=$(id -Gn $u | tr ' ' ',')
          echo "$u:$groups_list"
        done
      register: datos_linux
      changed_when: false

    # Windows: Formato "usuario:grupo1,grupo2"
    - name: Windows - Obtener todos los usuarios y sus grupos
      when: es_windows
      ansible.windows.win_shell: |
        Get-LocalUser | ForEach-Object {
            $name = $_.Name
            $groups = (Get-LocalGroup | Where-Object { (Get-LocalGroupMember -Group $_.Name).Name -contains "$env:COMPUTERNAME\$name" -or (Get-LocalGroupMember -Group $_.Name).Name -contains "AD-DOMAIN\$name" }).Name
            "$name:$($groups -join ',')"
        }
      register: datos_windows
      changed_when: false

    - name: Generar JSON con Usuarios y Permisos
      ansible.builtin.copy:
        dest: "{{ ruta_json_remoto }}"
        content: |
          {
            "inventory_hostname": "{{ inventory_hostname }}",
            "datos": {{ (es_windows | ternary(datos_windows.stdout_lines, datos_linux.stdout_lines)) | to_json }}
          }

    - name: Descargar JSON
      ansible.builtin.fetch:
        src: "{{ ruta_json_remoto }}"
        dest: "{{ ruta_json_ctl }}/"
        flat: true

##########################################################
# 2) Localhost: Procesar y crear Excel con 3 columnas    #
##########################################################
- name: Actualizar Excel
  hosts: localhost
  gather_facts: no
  vars:
    ruta_json_ctl: "/home/semaphore/Excels"
    ruta_excel:    "/home/semaphore/Excels/Inventario_Equipos_usuarios.xlsx"
    script_python: "/home/semaphore/Excels/append_excel2.py"
    venv_path:     "/home/semaphore/Excels/.venv"

  tasks:
    - name: Actualizar Script Python para 3 columnas
      ansible.builtin.copy:
        dest: "{{ script_python }}"
        mode: "0755"
        content: |
          #!/usr/bin/env python3
          import sys, os, json
          from openpyxl import Workbook, load_workbook

          def run():
              ex_p, j_p = sys.argv[1], sys.argv[2]
              with open(j_p, 'r') as f:
                  data = json.load(f)
              
              hn = data.get('inventory_hostname', 'Desconocido')
              filas = data.get('datos', [])

              if os.path.exists(ex_p):
                  wb = load_workbook(ex_p)
                  ws = wb.active
              else:
                  wb = Workbook()
                  ws = wb.active
                  ws.append(["Hostname", "Usuario", "Grupos/Permisos"])

              for linea in filas:
                  if ':' in linea:
                      user, groups = linea.split(':', 1)
                      ws.append([hn, user, groups])
              
              wb.save(ex_p)

          if __name__ == "__main__":
              run()

    - name: Ejecutar procesamiento
      ansible.builtin.shell: |
        {{ venv_path }}/bin/python {{ script_python }} {{ ruta_excel }} {{ item }}
      with_fileglob:
        - "{{ ruta_json_ctl }}/info_*.json"

##########################################################
# 3) Copiar al recurso de red (Igual que antes)          #
##########################################################
- name: Copiar Inventario al recurso de red
  hosts: localhost
  tasks:
    - name: Copiar Excel al Share
      become: true
      ansible.builtin.copy:
        src: "/home/semaphore/Excels/Inventario_Equipos_usuarios.xlsx"
        dest: "/mnt/ansible_share/Inventario_Usuarios_Completo.xlsx"
        mode: "0644"
        remote_src: true
