- name: Escanear red completa y detectar hosts activos
  hosts: localhost
  gather_facts: no
  vars:
    red: "10.57.3.0/24"  # Ajusta esto a tu red
  tasks:
    - name: Ejecutar escaneo ICMP con nmap
      ansible.builtin.command: nmap -sn {{ red }}
      register: resultado_escaneo
      changed_when: false

    - name: Extraer IPs activas de salida de nmap
      set_fact:
        ips_activas: "{{ resultado_escaneo.stdout_lines | select('match', '^Nmap scan report for ') | map('regex_replace', '^Nmap scan report for ', '') | list }}"

    - name: Mostrar IPs que responden al ping
      debug:
        msg: "{{ item }}"
      loop: "{{ ips_activas }}"
