- name: Verificar conexión con los equipos
  hosts: 10.57.3.0
  gather_facts: no
  tasks:
    - name: Prueba de respuesta de equipos con ping
      ansible.builtin.ping:
      register: resultado_ping

    - name: Mostrar resultado del ping
      debug:
        var: resultado_ping

