---
- name: Instalar 7-Zip en un equipo específico
  hosts: "{{ target_host }}" # Esta variable la recibirá desde Semaphore
  become: true
  tasks:
    - name: Instalar p7zip (Debian/Ubuntu)
      ansible.builtin.apt:
        name: p7zip-full
        state: present
      when: ansible_os_family == "Debian"

    - name: Instalar p7zip (RedHat/CentOS)
      ansible.builtin.dnf:
        name: p7zip
        state: present
      when: ansible_os_family == "RedHat"
