---
- name: Verificar conexión con los equipos
  hosts: localhost
  gather_facts: no

  vars:
    # Si no se proporciona, toma este valor por defecto (puedes cambiarlo o dejar vacío)
    target_ip: "{{ TARGET_IP | default('') }}"

- name: Instalar 7-Zip en un equipo específico
  hosts: "{{ target_host }}" # Esta variable la recibirá desde Semaphore
  become: true
  tasks:
    - name: Validar que se ha pasado una IP
      assert:
        that:
          - target_ip is match('^([0-9]{1,3}\\.){3}[0-9]{1,3}$')
        fail_msg: "❌ La variable TARGET_IP no está definida o no es una IP válida."

    - name: Hacer ping ICMP a {{ target_ip }}
      ansible.builtin.command:
        cmd: ping -c 1 -W 1 {{ target_ip }}
      register: resultado
      ignore_errors: true
    - name: Instalar p7zip (Debian/Ubuntu)
      ansible.builtin.apt:
        name: p7zip-full
        state: present
      when: ansible_os_family == "Debian"

    - name: Mostrar resultado del ping
      debug:
        msg: >-
          {% if resultado.rc == 0 %}
            ✅ {{ target_ip }} responde correctamente (RC={{ resultado.rc }})
          {% else %}
            ❌ {{ target_ip }} no responde (RC={{ resultado.rc }})
          {% endif %}
