---
- name: Auditoria de Puertos y Servicios
  hosts: semaforos
  become: yes
  gather_facts: no

  tasks:
    - name: "Capturar datos de red"
      ansible.builtin.shell: "ss -tunlp | grep LISTEN | awk '{print $1\"|\"$5\"|\"$7}'"
      register: raw_network_data
      changed_when: false

    - name: "Inicializar lista"
      set_fact:
        servicios_lista: []

    - name: "Procesar información"
      set_fact:
        servicios_lista: >-
          {{ 
            servicios_lista + 
            [{
              'puerto': item.split('|')[1].split(':')[-1],
              'proceso': item.split('"')[1] if '"' in item else 'desconocido'
            }] 
          }}
      loop: "{{ raw_network_data.stdout_lines }}"
      when: 
        - raw_network_data.stdout_lines is defined
        - item.split('|') | length >= 3
        - item is search('"')

    - name: "INFORME DE SERVICIOS ACTIVOS"
      ansible.builtin.debug:
        msg: |
          SERVICIOS EN {{ inventory_hostname }}:
          {% for svc in servicios_lista %}
          Port: {{ '%-6s' | format(svc.puerto) }} -> Service: {{ svc.proceso }}
          {% endfor %}
      when: servicios_lista | length > 0
